### ISSUE TITLE
.com missing

### ISSUE THREAD

**Issue by SiBell** [urbanobservatory/standards#4]
The url in the example needs .com adding, i.e. 

`https://api.urbanobservatory.com/birmingham/deployments/birmingham-weather-stations`

This was my mistake.

**Comment by lukeshope** [comment]
Cheers. I've amended the example to a more generic `api.example.com`, as part of my ridiculously optimistic aim that the standard might one day be used outside of the observatories.

**Comment by SiBell** [comment]
Good plan. Thanks for updating.
