### ISSUE TITLE
Links for quantities and units

### ISSUE THREAD

**Issue by SiBell** [urbanobservatory/standards#7]
Could do with adding a quick guide detailing where to find existing dictionaries of quantities and units. The hope being that the values we set for _observedProperty_ and _unit_ in our JSON-LD responses match those from other observatories.

I assume the main source of vocabulary would be [QUDT](http://www.linkedmodel.org/catalog/qudt/1.1/index.html), but it's not the easiest to search through.

**Comment by lukeshope** [comment]
Agreed. I also think QUDT has some omissions, especially in the context of air quality. Could you add to this list with anything slightly unusual you can think of so we can try find a good example for each?

* Air quality
  * Gas concentrations (ug/m3)
  * Gas concentrations (ppm/ppb)
  * Particle counts
* Water quality
  * Concentrations (mg/l)
  * Turbidity (NTU)
  * FDOM (quinine sulphate units)
  * Specific conductance (uS/cm)
* Climate
  * Air temperature
  * Precipitation intensity
  * Precipitation accumulation
  * Relative humidity
  * Wind speed
  * Wind direction
  * Soil temperature at depths
  * Station level atmospheric pressure
  * Mean sea level pressure
  * Lightning
* Counting
  * Vehicle and pedestrian counts
  * Directions of travel
* Other environmental
  * Noise levels
  * Light levels
* Infrastructure
  * Rail head moisture
  * Rail web temperature 
  * Road surface temperature

**Comment by SiBell** [comment]
Updated. Probably worth asking the other observatories too.

**Comment by EttoreHector** [comment]
Thank you, Luke.

That looks great already. I just wonder whether it is possible to add more hierarchical levels as in the following:

- **Environment**
  - _Air quality_
    - Gas concentrations (ug/m3)
    - Gas concentrations (ppm/ppb)
    - Particle counts
  -  _Water quality_
     - Concentrations (mg/l)
     - Turbidity (NTU)
     - FDOM (quinine sulphate units)
     - Specific conductance (uS/cm)
  - _Flood Monitoring_
    - Stage Water Level (m)
    - Under Stage Water Level (m)
- **Climate**
  - _Weather_
    - Precipitation Rate
    - Direct Solar Radiation
    - Atmospheric Pressure
    - etc.
  - _Etc_
- **Etc**

**Comment by EttoreHector** [comment]
Hi Luke and Simon.

As you already pointed out there are some omissions in QUDT, for example the typical concentration unit of pollutant level "micrograms per cubic meter".
How do we go around this? My understanding is that we have to define the new unit in terms of the "more standard" units present in QUDT (for example we'd have to define ug/m3 in terms of kg/m3). Is this correct? And if it is do you know how to proceed?

**Comment by lukeshope** [comment]
Hi Ettore,

We can define our own vocabulary if necessary. We would need to define a namespace for it and then describe the terms with some heirarchy and descriptions. As examples, the [W3C SSN](https://www.w3.org/ns/ssn/) is defined in Turtle and the [Hydra Core](https://www.w3.org/ns/hydra/core#) is defined in JSON-LD. I presume we'd prefer to use the latter.

I still find it hard to believe there's no vocabulary out there already that defines micrograms per cubic metre, but I also haven't found one. Crazy...

I think we'll need to define a handful of our own vocabulary terms as a minimum anyway.

**Comment by lukeshope** [comment]
Closing this because units are now being discussed alongside `observedProperty` types in #23.
